### ISSUE TITLE
A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by jnovack** [mtgatracker/mtgatracker#385]
Complete edge case, I fully understand if I'm the only person who has EVER had this problem.

I was attempting to delete the `output_log.txt` file within the window of the Settings -> Show Output_Log Directory at the same time while closing the game AND attempting to zip up the file.

Log file was over 1GB.

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property 'sender' of undefined
    at removeRemoteListenersAndLogWarning (C:\Users\GUEST\AppData\Local\mtgatracker\app-4.5.1\resources\electron.asar\browser\rpc-server.js:153:34)
    at callIntoRenderer (C:\Users\GUEST\AppData\Local\mtgatracker\app-4.5.1\resources\electron.asar\browser\rpc-server.js:220:13)
    at Function.wrappedCallback (C:\Users\GUEST\AppData\Local\mtgatracker\app-4.5.1\resources\electron.asar\browser\api\dialog.js:130:14)

**Comment by WizardRubic** [comment]
Is this reproducible on your end? I'm having trouble reproducing the error since Windows doesn't seem to like me deleting output_log.txt while the backend is using it. 

Based on that last part of the exception, I don't think there's anything we can do about it from our end if we choose to use the electron function([settingsRenderer.js#L226](https://github.com/mtgatracker/mtgatracker/blob/master/electron/settingsRenderer.js#L226)). The dialog.showOpenDialog() function is written so it'll callback our function to set filepath. According to [this SO post](https://stackoverflow.com/questions/7310521/node-js-best-practice-exception-handling) we can't surround the async code in a try catch or at least not easily.

What we could try is rewriting the function here to use an <input> element and handle the logic without the showOpenDialog function. I'm not sure this'll help fix it either though.

**Comment by jnovack** [comment]
I just want to report the error, a potential condition in the spot, maybe something was glaringly obvious or coded at 3am.

Like I said, I completely understand if this has a "happened once in a lifetime, not dedicating time to fix" tag and closed #wontfix
