### ISSUE TITLE
Show the draw probability for each card in decklist

### ISSUE THREAD

**Issue by axlan** [mtgatracker/mtgatracker#426]
Add an optional setting that can show the draw probability as a percentage next to each card.

**Comment by shawkinsl** [comment]
Howdy! Thanks for opening (and implementing) this issue! Unfortunately, I can't accept this issue; for now tracker functionality is being limited to things that any individual could reasonably accomplish with pen and paper--this just goes one step too far to assume all individuals could reasonably do this math, in their head or on paper--in order to try to keep usage of the tracker as a whole fair and "above board."
