### ISSUE TITLE
Warrant Canary for Modification Requests

### ISSUE THREAD

**Issue by jnovack** [mtgatracker/mtgatracker#447]
> or are asked by Wizards to modify the tracker in any way in order to stay in good standing

Request either

* a [canary statement](https://en.wikipedia.org/wiki/Warrant_canary) of "we have not been asked by Wizards to modify the tracker as yet" date if there's an NDA on data, or,
* listing the details of modifications requested by Wizards.

This is still considered an open-source project, the public should be notified of interference by a corporate entity.

**Comment by shawkinsl** [comment]
I personally consider this request to be pretty overkill, and I will say that this sort of assuming "they're out to get us" attitude is not exactly helpful in fostering an amicable relationship with WotC. I'd really like to do whatever I can to help anyone involved with the project discard these kinds of sentiments rather than encourage them. However, since my position could be considered not entirely unbiased anymore, I'll honor it for now.

WotC has a publicly published [fan-content policy](https://company.wizards.com/fancontentpolicy) that MTGATracker is bound under. Other than this, the only formal requests made so far have to do with _my_ ability to stay personally involved in the project. (MTGATracker certainly hasn't been "goldfished," though I admit that one entirely personal motivation of mine for allowing users to privately maintain their own data was to effectively preclude WotC from allowing itself to get that bad press once again, especially given that I'm not exactly interested in aggregating MTGA data at this time), because simply: bad stuff for WotC = bad stuff for MTGA = bad stuff for MTGA players like me.

I will also go ahead and state here and now that if WotC requested some kind of changes that I believe would overall harm MTGA players or MTGATracker users, I would simply recuse myself from the project rather than honor them.

https://blog.mtgatracker.com/private-modification-canary
